const WRONG_INPUT_VALUE = 'WRONG_INPUT_VALUE';
const MAIL_ALREADY_EXISTS = 'MAIL_ALREADY_EXISTS';
const USER_DOESNT_EXISTS = 'USER_DOESNT_EXISTS';
const WRONG_PASSWORD = 'WRONG_PASSWORD';

module.exports = {
  WRONG_INPUT_VALUE,
  MAIL_ALREADY_EXISTS,
  USER_DOESNT_EXISTS,
  WRONG_PASSWORD,
};
